name: Clone Private Repository and push it to idl-copy Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
    
  clone-copy-to-idl-copy:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout idl copies
        uses: actions/checkout@v3

      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-files: 'src/java/'
          destination-username: 'rajat71g'
          destination-repository: 'idl-copy'
          destination-directory: 'test/idl'
          commit-email: 'rajat71g@gmail.com'